# Generated by Django 4.2.7 on 2024-05-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_marketplace_expiry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
    ]
