# Generated by Django 4.2.7 on 2023-11-14 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_delete_orderdata_rename_flow_rate_suppliers_phone_no_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggestions',
        ),
    ]
