# Generated by Django 4.2.7 on 2024-05-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_graphpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphpoint',
            name='label',
            field=models.CharField(default='Default Label', max_length=100),
        ),
    ]
