# Generated by Django 4.2.7 on 2023-11-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_delete_suggestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='id',
        ),
        migrations.RemoveField(
            model_name='marketplace',
            name='id',
        ),
        migrations.RemoveField(
            model_name='predictions',
            name='id',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='id',
        ),
        migrations.AddField(
            model_name='inventory',
            name='item_id',
            field=models.CharField(default='some_default_value', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='marketplace',
            name='item_id',
            field=models.CharField(default='some_default_value', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='predictions',
            name='item_id',
            field=models.CharField(default='some_default_value', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='item_id',
            field=models.CharField(default='some_default_value', max_length=255, primary_key=True, serialize=False),
        ),
    ]
