# Generated by Django 4.2.7 on 2023-11-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_inventory_id_remove_marketplace_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item_id',
            field=models.PositiveIntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='marketplace',
            name='item_id',
            field=models.PositiveIntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='predictions',
            name='item_id',
            field=models.PositiveIntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='item_id',
            field=models.PositiveIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
