# Generated by Django 4.2.7 on 2024-05-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_graphpoint_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphpoint',
            name='x',
            field=models.DateField(),
        ),
    ]
